In [1]:
import pandas as pd

In [6]:
raw_dataset = "./data/CREDITRISK_RAW.xlsx"
score_dataset = "./data/CREDITRISK_SCORE.xlsx"

df = pd.read_excel(raw_dataset)
df_test = pd.read_excel(score_dataset)

In [7]:
df.head()

,ID,GENERO,RENTA,EDAD,NIV_EDUC,E_CIVIL,COD_OFI,COD_COM,CIUDAD,Crédito_1,Crédito_2,Crédito_3,Crédito_4,Monto solicitado,Días de Mora,Monto Deuda Promedio,Número de meses inactivo,numero de cuotas,Aval,PAGA
0,1,F,463000.0,55.0,MED,CAS,27,226,CONCEPCION,0,-4030,0.0,292673,142.0,0,81,1,18,NO,PAGA
1,2,F,1200000.0,59.0,MED,CAS,121,226,CONCEPCION,0,0,27797549.0,0,16.0,0,34519,1,60,NO,NO PAGA
2,3,F,526000.0,49.0,TEC,SEP,59,88,SANTIAGO,0,750000,0.0,0,0.0,0,8016,0,14,NO,NO PAGA
3,4,M,1500000.0,47.0,UNV,SEP,138,1,ARICA,0,976444,0.0,0,13.0,10,25323,1,66,NO,PAGA
4,5,M,2600000.0,41.0,UNV,CAS,60,291,PUERTO MONTT,0,115440,0.0,4500000,7960.0,14,4566,3,77,SI,NO PAGA